import jsPDF from 'jspdf';
import { SessionSummary, ProcessedEEGFrame } from '../types/eeg';

export interface ClinicalReportData {
  reportId: string;
  patientId: string;
  generatedAt: string;
  physicianAgent: string;
  summary: SessionSummary;
  frames: ProcessedEEGFrame[];
  analysisText: string;
  
  // Computed medical metrics
  signalQualityGrade: string;
  dominantRhythm: string;
  faaScore: number;
  faaValence: string;
  faaInterpretation: string;
  
  bandPower: {
    delta: { pct: string; bels: string; status: string };
    theta: { pct: string; bels: string; status: string };
    alpha: { pct: string; bels: string; status: string };
    beta: { pct: string; bels: string; status: string };
    gamma: { pct: string; bels: string; status: string };
  };

  channelPower: {
    AF7Alpha: string;
    AF8Alpha: string;
    TP9Alpha: string;
    TP10Alpha: string;
    frontalAvgAlpha: string;
    temporalAvgAlpha: string;
  };

  recommendations: string[];
}

export const generateMedicalReportPDF = (data: ClinicalReportData): void => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Colors
  const primaryColor = [15, 23, 42]; // slate-900
  const secondaryColor = [79, 70, 229]; // indigo-600
  const accentColor = [147, 51, 234]; // purple-600
  const lightBg = [248, 250, 252]; // slate-50
  const borderColor = [226, 232, 240]; // slate-200
  const darkTextColor = [30, 41, 59]; // slate-800
  const mutedTextColor = [100, 116, 139]; // slate-500

  // Helper: Header Banner
  const drawHeader = () => {
    // Top banner background
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, pageWidth, 28, 'F');

    // Decorative accent bar
    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.rect(0, 28, pageWidth, 1.5, 'F');

    // Title text
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('NEUROLOGICAL & COGNITIVE EEG DIAGNOSTIC REPORT', margin, 12);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(191, 219, 254);
    doc.text('Automated Deep AI Neural Agent Clinical Assessment | Confidential Diagnostic Document', margin, 18);

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.text(`REPORT ID: ${data.reportId}`, pageWidth - margin, 12, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.text(`DATE: ${data.generatedAt}`, pageWidth - margin, 18, { align: 'right' });

    y = 36;
  };

  // Helper: Footer
  const drawFooter = (pageNum: number, totalPages: number) => {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7.5);
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);

    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.text(
      'Medical Disclaimer: Generated by Mind Monitor Deep AI Neural Agent for clinical neurofeedback & cognitive assessment.',
      margin,
      pageHeight - 7
    );
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, pageHeight - 7, { align: 'right' });
  };

  // Check Page Break
  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 18) {
      doc.addPage();
      drawHeader();
    }
  };

  // START REPORT
  drawHeader();

  // --- SECTION 1: SUBJECT & RECORDING METADATA ---
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, y, contentWidth, 26, 2, 2, 'FD');

  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);

  // Column 1
  doc.text('Patient / Subject ID:', margin + 4, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(data.patientId, margin + 40, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Device Model:', margin + 4, y + 12);
  doc.setFont('helvetica', 'normal');
  doc.text('Muse 2/S (4 Sensor Electrodes)', margin + 40, y + 12);

  doc.setFont('helvetica', 'bold');
  doc.text('Electrode Layout:', margin + 4, y + 18);
  doc.setFont('helvetica', 'normal');
  doc.text('AF7, AF8 (Frontal), TP9, TP10 (Temporal)', margin + 40, y + 18);

  // Column 2
  const col2X = margin + 100;
  doc.setFont('helvetica', 'bold');
  doc.text('Recording Duration:', col2X, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(data.summary.totalDurationFormatted, col2X + 38, y + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Samples Analyzed:', col2X, y + 12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.summary.totalSamples.toLocaleString()} frames`, col2X + 38, y + 12);

  doc.setFont('helvetica', 'bold');
  doc.text('Signal Contact Quality:', col2X, y + 18);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(16, 185, 129); // emerald
  doc.text(`${data.summary.dataQualityPercent}% (${data.signalQualityGrade})`, col2X + 38, y + 18);

  y += 32;

  // --- SECTION 2: EXECUTIVE CLINICAL IMPRESSION ---
  checkPageBreak(30);

  doc.setFillColor(243, 244, 246);
  doc.setDrawColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setLineWidth(1);
  doc.rect(margin, y, contentWidth, 24, 'FD');

  doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.rect(margin, y, 3, 24, 'F');

  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('CLINICAL IMPRESSION & NEUROLOGICAL STATE SUMMARY', margin + 7, y + 7);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.text(`Primary Neuro-State: ${data.dominantRhythm}`, margin + 7, y + 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  const splitSummary = doc.splitTextToSize(
    `The recording exhibits clean electroencephalographic rhythms with an overall signal contact efficiency of ${data.summary.dataQualityPercent}%. Frontal Alpha Asymmetry (FAA) measures ${data.faaScore.toFixed(3)} Bels (${data.faaValence}), reflecting ${data.faaInterpretation}.`,
    contentWidth - 12
  );
  doc.text(splitSummary, margin + 7, y + 18);

  y += 30;

  // --- SECTION 3: SPECTRAL POWER DENSITY BREAKDOWN ---
  checkPageBreak(50);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('1. Spectral Power Density (PSD) & Frequency Band Diagnostics', margin, y);
  y += 4;

  // Table Header
  const tableHeaders = ['Frequency Band', 'Hz Range', 'Rel Power %', 'Power (Bels)', 'Clinical Diagnostic Interpretation'];
  const colWidths = [32, 22, 24, 25, 77];
  
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(margin, y, contentWidth, 7, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);

  let xPos = margin + 2;
  tableHeaders.forEach((hdr, idx) => {
    doc.text(hdr, xPos, y + 4.5);
    xPos += colWidths[idx];
  });

  y += 7;

  // Table Rows
  const rows = [
    { name: 'Delta (δ)', hz: '1.0 - 4.0 Hz', pct: `${data.bandPower.delta.pct}%`, bels: `${data.bandPower.delta.bels} Bels`, desc: 'Deep restorative rest / slow-wave sleep activity' },
    { name: 'Theta (θ)', hz: '4.0 - 8.0 Hz', pct: `${data.bandPower.theta.pct}%`, bels: `${data.bandPower.theta.bels} Bels`, desc: 'Deep meditation, memory encoding & creative flow' },
    { name: 'Alpha (α)', hz: '7.5 - 13.0 Hz', pct: `${data.bandPower.alpha.pct}%`, bels: `${data.bandPower.alpha.bels} Bels`, desc: 'Relaxed alertness, calm focus & cortical readiness' },
    { name: 'Beta (β)', hz: '13.0 - 30.0 Hz', pct: `${data.bandPower.beta.pct}%`, bels: `${data.bandPower.beta.bels} Bels`, desc: 'Active cognitive processing, problem solving & attention' },
    { name: 'Gamma (γ)', hz: '30.0 - 44.0 Hz', pct: `${data.bandPower.gamma.pct}%`, bels: `${data.bandPower.gamma.bels} Bels`, desc: 'High-level information synthesis & peak cognitive bind' },
  ];

  rows.forEach((r, idx) => {
    const bg = idx % 2 === 0 ? [255, 255, 255] : [248, 250, 252];
    doc.setFillColor(bg[0], bg[1], bg[2]);
    doc.rect(margin, y, contentWidth, 6.5, 'F');

    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.2);
    doc.line(margin, y + 6.5, margin + contentWidth, y + 6.5);

    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.setFont('helvetica', idx === 2 ? 'bold' : 'normal'); // highlight alpha
    doc.setFontSize(7.5);

    let rowX = margin + 2;
    doc.text(r.name, rowX, y + 4.5); rowX += colWidths[0];
    doc.text(r.hz, rowX, y + 4.5); rowX += colWidths[1];
    doc.text(r.pct, rowX, y + 4.5); rowX += colWidths[2];
    doc.text(r.bels, rowX, y + 4.5); rowX += colWidths[3];
    doc.text(r.desc, rowX, y + 4.5);

    y += 6.5;
  });

  y += 8;

  // --- SECTION 4: SPATIAL TOPOGRAPHY & FAA HEMISPHERIC VALENCE ---
  checkPageBreak(40);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('2. Regional Electrode Topography & Hemispheric Balance (FAA)', margin, y);
  y += 5;

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, 24, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

  doc.text(`Frontal Alpha Asymmetry (FAA Index): ${data.faaScore.toFixed(3)} Bels`, margin + 4, y + 6);
  doc.text(`Hemispheric Valence: ${data.faaValence}`, margin + 100, y + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text(`Frontal Cortex (AF7 Left: ${data.channelPower.AF7Alpha} Bels, AF8 Right: ${data.channelPower.AF8Alpha} Bels | Avg: ${data.channelPower.frontalAvgAlpha} Bels)`, margin + 4, y + 12);
  doc.text(`Temporal Lobes (TP9 Left: ${data.channelPower.TP9Alpha} Bels, TP10 Right: ${data.channelPower.TP10Alpha} Bels | Avg: ${data.channelPower.temporalAvgAlpha} Bels)`, margin + 4, y + 17);
  doc.text(`Clinical Orientation: ${data.faaInterpretation}`, margin + 4, y + 22);

  y += 30;

  // --- SECTION 5: QUANTITATIVE COGNITIVE INDICES ---
  checkPageBreak(35);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('3. Quantitative Neuro-Cognitive Scores (0 - 100 Clinical Index)', margin, y);
  y += 5;

  const scoreBoxWidth = (contentWidth - 9) / 4;
  const scores = [
    { label: 'Focus / Engagement', score: data.summary.avgFocus, color: [79, 70, 229] },
    { label: 'Tranquility / Calm', score: data.summary.avgCalm, color: [16, 185, 129] },
    { label: 'Meditation Depth', score: data.summary.avgMeditationDepth, color: [147, 51, 234] },
    { label: 'Mental Workload', score: data.summary.avgCognitiveLoad, color: [245, 158, 11] },
  ];

  scores.forEach((s, idx) => {
    const sbX = margin + idx * (scoreBoxWidth + 3);
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(s.color[0], s.color[1], s.color[2]);
    doc.setLineWidth(0.6);
    doc.roundedRect(sbX, y, scoreBoxWidth, 18, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(s.color[0], s.color[1], s.color[2]);
    doc.text(`${s.score}/100`, sbX + scoreBoxWidth / 2, y + 9, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.text(s.label, sbX + scoreBoxWidth / 2, y + 15, { align: 'center' });
  });

  y += 24;

  // --- SECTION 6: DETAILED CLINICAL AI REPORT TEXT ---
  checkPageBreak(50);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('4. Deep Agent Neuro-Diagnostic Analysis & Protocols', margin, y);
  y += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

  const cleanAnalysisText = data.analysisText
    .replace(/#/g, '')
    .replace(/\*\*/g, '')
    .trim();

  const splitAnalysis = doc.splitTextToSize(cleanAnalysisText, contentWidth);

  splitAnalysis.forEach((line: string) => {
    checkPageBreak(5);
    doc.text(line, margin, y);
    y += 4;
  });

  y += 6;

  // --- SIGNATURE & VERIFICATION BLOCK ---
  checkPageBreak(30);

  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.3);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('Certified Neural Agent Clinical Verification:', margin, y);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.text(`Physician Agent: ${data.physicianAgent}`, margin, y + 5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text('Verification Code: EEG-AGENT-VERIFIED-3.6-FLASH', pageWidth - margin, y + 5, { align: 'right' });

  // Add Page Numbers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  // Save PDF
  doc.save(`EEG_Clinical_Neuro_Report_${data.reportId}.pdf`);
};
