import jsPDF from 'jspdf';
import { SessionSummary, ProcessedEEGFrame } from '../types/eeg';
import { StructuredClinicalReport } from './clinicalEngine';
import { MultiStepAuditOutput } from './llmClient';
import { SessionComparisonResult } from './sessionComparator';

export interface ClinicalReportData {
  reportId: string;
  patientId: string;
  generatedAt: string;
  physicianAgent: string;
  summary: SessionSummary;
  frames: ProcessedEEGFrame[];
  analysisText: string;
  
  // Computed medical metrics
  signalQualityGrade: string;
  dominantRhythm: string;
  faaScore: number;
  faaValence: string;
  faaInterpretation: string;
  
  bandPower: {
    delta: { pct: string; bels: string; status: string };
    theta: { pct: string; bels: string; status: string };
    alpha: { pct: string; bels: string; status: string };
    beta: { pct: string; bels: string; status: string };
    gamma: { pct: string; bels: string; status: string };
  };

  channelPower: {
    AF7Alpha: string;
    AF8Alpha: string;
    TP9Alpha: string;
    TP10Alpha: string;
    frontalAvgAlpha: string;
    temporalAvgAlpha: string;
  };

  recommendations: string[];
  report?: StructuredClinicalReport;
  auditOutput?: MultiStepAuditOutput | null;
}

export interface DualSessionReportData {
  reportId: string;
  generatedAt: string;
  sessionA: { filename: string; summary: SessionSummary; frames: ProcessedEEGFrame[] };
  sessionB: { filename: string; summary: SessionSummary; frames: ProcessedEEGFrame[] };
  comparisonResult: SessionComparisonResult;
  auditOutput?: MultiStepAuditOutput | null;
}

export const generateMedicalReportPDF = (data: ClinicalReportData): void => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Color Palette - Medical Professional Slate/Indigo
  const primaryColor = [15, 23, 42]; // slate-900
  const secondaryColor = [79, 70, 229]; // indigo-600
  const accentColor = [147, 51, 234]; // purple-600
  const lightBg = [248, 250, 252]; // slate-50
  const cardBg = [241, 245, 249]; // slate-100
  const borderColor = [226, 232, 240]; // slate-200
  const darkTextColor = [30, 41, 59]; // slate-800
  const mutedTextColor = [100, 116, 139]; // slate-500

  // Helper: Header Banner
  const drawHeader = (customTitle?: string) => {
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, pageWidth, 24, 'F');

    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.rect(0, 24, pageWidth, 1.2, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text(customTitle || 'EEG ANALYSIS REPORT', margin, 11);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(191, 219, 254);
    doc.text('EEG Mind Analyzer | Session Report', margin, 18);

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`REPORT ID: ${data.reportId}`, pageWidth - margin, 11, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.text(`DATE: ${data.generatedAt}`, pageWidth - margin, 18, { align: 'right' });

    y = 30;
  };

  // Helper: Footer
  const drawFooter = (pageNum: number, totalPages: number) => {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);

    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 10, pageWidth - margin, pageHeight - 10);

    const isAi = data.auditOutput?.isAiGenerated ?? false;
    const modeLabel = isAi
      ? `Live Model (${data.auditOutput?.providerUsed.toUpperCase()})`
      : 'Rule-Based Deterministic Engine (Offline / Rule-Based)';

    doc.text(
      `Generated by EEG Mind Analyzer | Evaluation Mode: ${modeLabel}`,
      margin,
      pageHeight - 5
    );
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, pageHeight - 5, { align: 'right' });
  };

  // ==========================================
  // PAGE 1: METADATA, IMPRESSION, PSD TABLE, TOPOGRAPHY
  // ==========================================
  drawHeader();

  // --- SECTION 1: SUBJECT & RECORDING METADATA ---
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, y, contentWidth, 36, 2, 2, 'FD');

  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);

  doc.text('Patient / Subject ID:', margin + 4, y + 6.5);
  doc.setFont('helvetica', 'normal');
  doc.text(data.patientId, margin + 42, y + 6.5);

  doc.setFont('helvetica', 'bold');
  doc.text('Device Model:', margin + 4, y + 13.5);
  doc.setFont('helvetica', 'normal');
  doc.text('Muse 2/S (4 Sensor Electrodes)', margin + 42, y + 13.5);

  doc.setFont('helvetica', 'bold');
  doc.text('Electrode Layout:', margin + 4, y + 20.5);
  doc.setFont('helvetica', 'normal');
  doc.text('AF7, AF8 (Frontal), TP9, TP10 (Temporal)', margin + 42, y + 20.5);

  doc.setFont('helvetica', 'bold');
  doc.text('Assessment Mode:', margin + 4, y + 27.5);
  doc.setFont('helvetica', 'normal');
  const isAiReport = data.auditOutput?.isAiGenerated ?? false;
  if (isAiReport) {
    doc.setTextColor(16, 185, 129);
    doc.text(`Live Model (${data.auditOutput?.providerUsed.toUpperCase()} - ${data.auditOutput?.modelUsed})`, margin + 42, y + 27.5);
  } else {
    doc.setTextColor(217, 119, 6);
    doc.text('Rule-Based Engine (Offline / No API Key Provided)', margin + 42, y + 27.5);
  }
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

  const col2X = margin + 102;
  doc.setFont('helvetica', 'bold');
  doc.text('Recording Duration:', col2X, y + 6.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.summary.totalDurationFormatted}${data.summary.sessionDateFormatted ? ` (${data.summary.sessionDateFormatted})` : ''}`, col2X + 40, y + 6.5);

  doc.setFont('helvetica', 'bold');
  doc.text('Samples Analyzed:', col2X, y + 13.5);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.summary.totalSamples.toLocaleString()} frames`, col2X + 40, y + 13.5);

  doc.setFont('helvetica', 'bold');
  doc.text('Signal Contact Quality:', col2X, y + 20.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(16, 185, 129);
  doc.text(`${data.summary.dataQualityPercent}% (${data.signalQualityGrade})`, col2X + 40, y + 20.5);

  y += 42;

  // --- SECTION 2: EXECUTIVE CLINICAL IMPRESSION ---
  doc.setFillColor(243, 244, 246);
  doc.setDrawColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setLineWidth(0.8);
  doc.roundedRect(margin, y, contentWidth, 32, 2, 2, 'FD');

  doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.rect(margin, y, 3, 32, 'F');

  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.text('CLINICAL IMPRESSION & NEUROLOGICAL STATE SUMMARY', margin + 6, y + 7);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  const execHeadline = data.auditOutput?.executiveSummary?.executiveHeadline || `Primary Neuro-State: ${data.dominantRhythm} Dominance`;
  doc.text(execHeadline.slice(0, 85), margin + 6, y + 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  const summaryText = data.auditOutput?.executiveSummary?.keyTakeaways?.[0] ||
    data.report?.findings.clinicalSummaryText ||
    `The recording exhibits clean electroencephalographic rhythms with an overall signal contact efficiency of ${data.summary.dataQualityPercent}%. Frontal Alpha Asymmetry (FAA) measures ${data.faaScore.toFixed(3)} Bels (${data.faaValence}), reflecting ${data.faaInterpretation}.`;
  
  const splitSummary = doc.splitTextToSize(summaryText, contentWidth - 10);
  doc.text(splitSummary, margin + 6, y + 20);

  y += 38;

  // --- SECTION 3: SPECTRAL POWER DENSITY (PSD) BREAKDOWN TABLE ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('1. Spectral Power Density (PSD) & Frequency Band Diagnostics', margin, y);
  y += 5;

  const tableHeaders = ['Frequency Band', 'Hz Range', 'Rel Power %', 'Power (Bels)', 'Clinical Diagnostic Interpretation'];
  const colWidths = [32, 24, 25, 25, 80];
  
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(margin, y, contentWidth, 7.5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);

  let xPos = margin + 2;
  tableHeaders.forEach((hdr, idx) => {
    doc.text(hdr, xPos, y + 5.2);
    xPos += colWidths[idx];
  });

  y += 7.5;

  const rows = [
    { name: 'Delta (δ)', hz: '1.0 - 4.0 Hz', pct: `${data.bandPower.delta.pct}%`, bels: `${data.bandPower.delta.bels} Bels`, desc: 'Deep restorative slow-wave activity; motor inhibition baseline' },
    { name: 'Theta (θ)', hz: '4.0 - 8.0 Hz', pct: `${data.bandPower.theta.pct}%`, bels: `${data.bandPower.theta.bels} Bels`, desc: 'Deep meditation, memory encoding, limbic activity & creative flow' },
    { name: 'Alpha (α)', hz: '7.5 - 13.0 Hz', pct: `${data.bandPower.alpha.pct}%`, bels: `${data.bandPower.alpha.bels} Bels`, desc: 'Relaxed alertness, cortical readiness & parasympathetic dominance' },
    { name: 'Beta (β)', hz: '13.0 - 30.0 Hz', pct: `${data.bandPower.beta.pct}%`, bels: `${data.bandPower.beta.bels} Bels`, desc: 'Active prefrontal cognitive processing & task-oriented attention' },
    { name: 'Gamma (γ)', hz: '30.0 - 44.0 Hz', pct: `${data.bandPower.gamma.pct}%`, bels: `${data.bandPower.gamma.bels} Bels`, desc: 'High-frequency sensory binding & peak cognitive focus state' },
  ];

  rows.forEach((r, idx) => {
    const bg = idx % 2 === 0 ? [255, 255, 255] : [248, 250, 252];
    doc.setFillColor(bg[0], bg[1], bg[2]);
    doc.rect(margin, y, contentWidth, 7, 'F');

    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.2);
    doc.line(margin, y + 7, margin + contentWidth, y + 7);

    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.setFont('helvetica', r.name.toLowerCase().includes(data.dominantRhythm.toLowerCase()) ? 'bold' : 'normal');
    doc.setFontSize(9.5);

    let rowX = margin + 2;
    doc.text(r.name, rowX, y + 4.8); rowX += colWidths[0];
    doc.text(r.hz, rowX, y + 4.8); rowX += colWidths[1];
    doc.text(r.pct, rowX, y + 4.8); rowX += colWidths[2];
    doc.text(r.bels, rowX, y + 4.8); rowX += colWidths[3];
    doc.text(r.desc, rowX, y + 4.8);

    y += 7;
  });

  y += 8;

  // --- SECTION 4: SPATIAL TOPOGRAPHY & FAA ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('2. Regional Electrode Topography & Hemispheric Balance (FAA)', margin, y);
  y += 5;

  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, 30, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

  doc.text(`Frontal Alpha Asymmetry (FAA Index): ${data.faaScore.toFixed(3)} Bels`, margin + 4, y + 7);
  doc.text(`Hemispheric Valence: ${data.faaValence}`, margin + 100, y + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text(`Frontal Cortex (AF7 Left: ${data.channelPower.AF7Alpha} Bels, AF8 Right: ${data.channelPower.AF8Alpha} Bels | Avg: ${data.channelPower.frontalAvgAlpha} Bels)`, margin + 4, y + 14);
  doc.text(`Temporal Lobes (TP9 Left: ${data.channelPower.TP9Alpha} Bels, TP10 Right: ${data.channelPower.TP10Alpha} Bels | Avg: ${data.channelPower.temporalAvgAlpha} Bels)`, margin + 4, y + 20);
  doc.text(`Clinical Orientation: ${data.faaInterpretation}`, margin + 4, y + 26);

  // ==========================================
  // PAGE 2: COGNITIVE SCORES, TIMELINE, AI AUDIT STEPS
  // ==========================================
  doc.addPage();
  drawHeader();

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('3. Quantitative Neuro-Cognitive Scores (0 - 100 Clinical Index)', margin, y);
  y += 5;

  const scoreBoxWidth = (contentWidth - 9) / 4;
  const scores = [
    { label: 'Focus / Engagement', score: data.summary.avgFocus, color: [79, 70, 229] },
    { label: 'Tranquility / Calm', score: data.summary.avgCalm, color: [16, 185, 129] },
    { label: 'Meditation Depth', score: data.summary.avgMeditationDepth, color: [147, 51, 234] },
    { label: 'Mental Workload', score: data.summary.avgCognitiveLoad, color: [245, 158, 11] },
  ];

  scores.forEach((s, idx) => {
    const sbX = margin + idx * (scoreBoxWidth + 3);
    doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
    doc.setDrawColor(s.color[0], s.color[1], s.color[2]);
    doc.setLineWidth(0.6);
    doc.roundedRect(sbX, y, scoreBoxWidth, 20, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.setTextColor(s.color[0], s.color[1], s.color[2]);
    doc.text(`${s.score}/100`, sbX + scoreBoxWidth / 2, y + 10, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.text(s.label, sbX + scoreBoxWidth / 2, y + 16, { align: 'center' });
  });

  y += 26;

  // --- SECTION 4: CLINICAL ASSESSMENT ---
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('4. Clinical Assessment', margin, y);
  y += 6;

  const auditStepsToPrint = data.auditOutput?.steps || [];
  if (auditStepsToPrint.length > 0) {
    auditStepsToPrint.forEach((st) => {
      if (y > pageHeight - 35) {
        doc.addPage();
        drawHeader();
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);

      const cleanDetails = st.detailsMarkdown.replace(/#+\s*/g, '').trim();
      const splitText = doc.splitTextToSize(cleanDetails, contentWidth - 8);
      const lineSpacing = 4.8;
      const textHeight = splitText.length * lineSpacing;
      const boxHeight = textHeight + 12;

      if (y + boxHeight > pageHeight - 20) {
        doc.addPage();
        drawHeader();
      }

      doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
      doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, y, contentWidth, boxHeight, 1.5, 1.5, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.text(`Step ${st.stepNumber}: ${st.stepTitle}`, margin + 4, y + 6);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
      
      doc.text(splitText, margin + 4, y + 12);

      y += boxHeight + 5;
    });
  } else {
    // Fallback static observations
    const observations = data.report?.findings.diagnosticObservations || [
      `Frontal Alpha Asymmetry of ${data.faaScore.toFixed(3)} Bels indicates ${data.faaValence.toLowerCase()} emotional orientation.`,
      `Dominant power frequency isolated in the ${data.dominantRhythm} band (${data.bandPower[data.dominantRhythm.toLowerCase() as keyof typeof data.bandPower]?.pct || '35'}% total power).`,
      `Signal artifact rejection audit passed with ${data.summary.dataQualityPercent}% contact cleanliness.`,
    ];

    doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, y, contentWidth, 30, 2, 2, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

    let obsY = y + 7;
    observations.slice(0, 3).forEach((obs) => {
      doc.text(`•  ${obs}`, margin + 4, obsY);
      obsY += 7;
    });
    y += 34;
  }

  // Check page height for biofeedback protocols & signature
  if (y > pageHeight - 50) {
    doc.addPage();
    drawHeader();
  }

  // --- SECTION 5: PRESCRIBED BIOFEEDBACK PROTOCOLS & ACTION PLAN ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('5. Actionable Biofeedback Protocols & Roadmap', margin, y);
  y += 5;

  const protocols = data.auditOutput?.executiveSummary?.topRecommendations?.map((r, i) => ({
    title: `Protocol ${i + 1}`,
    mechanism: r,
    dosage: 'Daily Practice'
  })) || data.report?.findings.protocols || [
    { title: 'Resonant Frequency Breathing (6 Breaths/Min)', category: 'Autonomic Protocol', dosage: '10 mins pre-work', mechanism: 'Elevates Frontal Alpha power and regulates autonomic nervous tone.' },
    { title: 'Pomodoro SMR Task Structuring (25m / 5m Rest)', category: 'Focus Maintenance', dosage: 'Daily workflow', mechanism: 'Mitigates prefrontal Beta fatigue and preserves cognitive workload reserve.' },
    { title: 'Theta-Alpha Entrainment Meditation', category: 'Restorative Protocol', dosage: '15 mins post-work', mechanism: 'Promotes temporal TP9/TP10 Theta-Alpha synchrony for stress recovery.' },
  ];

  protocols.forEach((prot: any, protIdx: number) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.8);
    const recText = doc.splitTextToSize(`Recommendation: ${prot.mechanism}`, contentWidth - 8);
    const protBoxHeight = Math.max(14, recText.length * 4.2 + 8);

    if (y + protBoxHeight > pageHeight - 20) {
      doc.addPage();
      drawHeader();
    }

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, y, contentWidth, protBoxHeight, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.text(`${protIdx + 1}. ${prot.title}`, margin + 4, y + 5.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.8);
    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.text(recText, margin + 4, y + 10.5);

    y += protBoxHeight + 4;
  });

  y += 4;

  // --- SECTION 6: AUTOMATED REPORT VERIFICATION ---
  if (y > pageHeight - 25) {
    doc.addPage();
    drawHeader();
  }

  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.4);
  doc.line(margin, y, margin + contentWidth, y);
  y += 5;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('Automated Report Verification:', margin, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.text(`Analysis Engine: ${data.physicianAgent || 'Mind Monitor Clinical Engine'}`, margin, y + 5.5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text('Verification Status: Signal & Spectral Processing Verified', pageWidth - margin, y + 5.5, { align: 'right' });

  // Add Footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  doc.save(`EEG_Clinical_Neuro_Report_${data.reportId}.pdf`);
};

/**
 * Generate PDF report for Dual Session Comparative Analytics
 */
export const generateComparativeReportPDF = (data: DualSessionReportData): void => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const primaryColor = [15, 23, 42]; // slate-900
  const secondaryColor = [8, 145, 178]; // cyan-600
  const accentColor = [124, 58, 237]; // violet-600
  const lightBg = [248, 250, 252];
  const cardBg = [241, 245, 249];
  const borderColor = [226, 232, 240];
  const darkTextColor = [30, 41, 59];
  const mutedTextColor = [100, 116, 139];

  const drawHeader = () => {
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, pageWidth, 24, 'F');

    doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
    doc.rect(0, 24, pageWidth, 1.2, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('EEG SESSION COMPARISON REPORT', margin, 11);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(165, 243, 252);
    doc.text('EEG Mind Analyzer | Comparative Analysis', margin, 18);

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`REPORT ID: ${data.reportId}`, pageWidth - margin, 11, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.text(`DATE: ${data.generatedAt}`, pageWidth - margin, 18, { align: 'right' });

    y = 30;
  };

  const drawFooter = (pageNum: number, totalPages: number) => {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);

    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 10, pageWidth - margin, pageHeight - 10);

    const isAi = data.auditOutput?.isAiGenerated ?? false;
    const modeLabel = isAi
      ? `Live Model (${data.auditOutput?.providerUsed.toUpperCase()})`
      : 'Rule-Based Deterministic Engine (Offline / Rule-Based)';

    doc.text(
      `Generated by EEG Mind Analyzer | Evaluation Mode: ${modeLabel}`,
      margin,
      pageHeight - 5
    );
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, pageHeight - 5, { align: 'right' });
  };

  // PAGE 1
  drawHeader();

  // SECTION 1: METADATA COMPARISON
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, y, contentWidth, 30, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

  doc.text(`Session A (Baseline):`, margin + 4, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.sessionA.filename} (${data.comparisonResult.sessionAInfo.duration}, ${data.comparisonResult.sessionAInfo.quality}% clean)`, margin + 42, y + 7);

  doc.setFont('helvetica', 'bold');
  doc.text(`Session B (Comparison):`, margin + 4, y + 14);
  doc.setFont('helvetica', 'normal');
  doc.text(`${data.sessionB.filename} (${data.comparisonResult.sessionBInfo.duration}, ${data.comparisonResult.sessionBInfo.quality}% clean)`, margin + 42, y + 14);

  doc.setFont('helvetica', 'bold');
  doc.text(`Signal Quality Delta:`, margin + 4, y + 21);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(data.comparisonResult.overviewDeltas.qualityDelta >= 0 ? 16 : 225, 185, 129);
  doc.text(`${data.comparisonResult.overviewDeltas.qualityDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.qualityDelta}%`, margin + 42, y + 21);

  y += 35;

  // SECTION 2: EXECUTIVE SHIFT CARD
  doc.setFillColor(243, 244, 246);
  doc.setDrawColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setLineWidth(0.8);
  doc.roundedRect(margin, y, contentWidth, 32, 2, 2, 'FD');

  doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.rect(margin, y, 3, 32, 'F');

  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.text('EXECUTIVE STATE TRANSITION & CLINICAL IMPRESSION', margin + 6, y + 7);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  const execHeadline = data.auditOutput?.executiveSummary?.executiveHeadline || 'Cross-Session State Adaptation & Shift';
  doc.text(execHeadline.slice(0, 85), margin + 6, y + 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  const splitText = doc.splitTextToSize(
    data.auditOutput?.executiveSummary?.keyTakeaways?.[0] ||
    `Transition from Session A (${data.sessionA.summary.dominantWave}) to Session B (${data.sessionB.summary.dominantWave}). Tranquility shifted by ${data.comparisonResult.overviewDeltas.calmDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.calmDelta} points and Focus shifted by ${data.comparisonResult.overviewDeltas.focusDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.focusDelta} points.`,
    contentWidth - 10
  );
  doc.text(splitText, margin + 6, y + 20);

  y += 38;

  // SECTION 3: COGNITIVE SCORE DELTAS
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('1. Core Cognitive Score Deltas (Session A vs Session B)', margin, y);
  y += 5;

  const scoreBoxWidth = (contentWidth - 9) / 4;
  const deltas = [
    { label: 'Tranquility Shift', value: `${data.comparisonResult.overviewDeltas.calmDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.calmDelta} pts`, color: [16, 185, 129] },
    { label: 'Focus Shift', value: `${data.comparisonResult.overviewDeltas.focusDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.focusDelta} pts`, color: [79, 70, 229] },
    { label: 'FAA Valence Shift', value: `${data.comparisonResult.overviewDeltas.faaDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.faaDelta.toFixed(3)} Bels`, color: [147, 51, 234] },
    { label: 'Workload Shift', value: `${data.comparisonResult.overviewDeltas.loadDelta > 0 ? '+' : ''}${data.comparisonResult.overviewDeltas.loadDelta} pts`, color: [245, 158, 11] },
  ];

  deltas.forEach((d, idx) => {
    const sbX = margin + idx * (scoreBoxWidth + 3);
    doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
    doc.setDrawColor(d.color[0], d.color[1], d.color[2]);
    doc.setLineWidth(0.6);
    doc.roundedRect(sbX, y, scoreBoxWidth, 20, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(d.color[0], d.color[1], d.color[2]);
    doc.text(d.value, sbX + scoreBoxWidth / 2, y + 10, { align: 'center' });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.text(d.label, sbX + scoreBoxWidth / 2, y + 16, { align: 'center' });
  });

  y += 26;

  // SECTION 4: 4-SENSOR SPATIAL POWER SHIFTS TABLE
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('2. 4-Sensor Spatial Power Shifts (AF7, AF8, TP9, TP10)', margin, y);
  y += 5;

  const tableHeaders = ['Sensor', 'Delta (δ)', 'Theta (θ)', 'Alpha (α)', 'Beta (β)', 'Gamma (γ)'];
  const colW = [30, 31, 31, 31, 31, 32];

  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(margin, y, contentWidth, 7, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);

  let xP = margin + 2;
  tableHeaders.forEach((hdr, idx) => {
    doc.text(hdr, xP, y + 4.8);
    xP += colW[idx];
  });

  y += 7;

  const sensors = ['AF7', 'AF8', 'TP9', 'TP10'] as const;
  sensors.forEach((s, idx) => {
    const bg = idx % 2 === 0 ? [255, 255, 255] : [248, 250, 252];
    const sStats = data.comparisonResult.sensorStats[s].deltas;

    doc.setFillColor(bg[0], bg[1], bg[2]);
    doc.rect(margin, y, contentWidth, 7, 'F');

    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.2);
    doc.line(margin, y + 7, margin + contentWidth, y + 7);

    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);

    let rowX = margin + 2;
    doc.text(s, rowX, y + 4.8); rowX += colW[0];
    doc.setFont('helvetica', 'normal');
    doc.text(`${sStats.delta > 0 ? '+' : ''}${sStats.delta}`, rowX, y + 4.8); rowX += colW[1];
    doc.text(`${sStats.theta > 0 ? '+' : ''}${sStats.theta}`, rowX, y + 4.8); rowX += colW[2];
    doc.text(`${sStats.alpha > 0 ? '+' : ''}${sStats.alpha}`, rowX, y + 4.8); rowX += colW[3];
    doc.text(`${sStats.beta > 0 ? '+' : ''}${sStats.beta}`, rowX, y + 4.8); rowX += colW[4];
    doc.text(`${sStats.gamma > 0 ? '+' : ''}${sStats.gamma}`, rowX, y + 4.8);

    y += 7;
  });

  // PAGE 2
  doc.addPage();
  drawHeader();

  // SECTION 5: MULTI-STEP COMPARATIVE AUDIT STEPS
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('3. Comparative Assessment', margin, y);
  y += 6;

  const stepsToPrint = data.auditOutput?.steps || [];
  if (stepsToPrint.length > 0) {
    stepsToPrint.forEach((st) => {
      if (y > pageHeight - 35) {
        doc.addPage();
        drawHeader();
      }

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);

      const cleanDetails = st.detailsMarkdown.replace(/#+\s*/g, '').trim();
      const splitLines = doc.splitTextToSize(cleanDetails, contentWidth - 8);
      const lineSpacing = 4.8;
      const textHeight = splitLines.length * lineSpacing;
      const boxH = textHeight + 12;

      if (y + boxH > pageHeight - 20) {
        doc.addPage();
        drawHeader();
      }

      doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
      doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, y, contentWidth, boxH, 1.5, 1.5, 'FD');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      doc.text(`Comparative Step ${st.stepNumber}: ${st.stepTitle}`, margin + 4, y + 6);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

      doc.text(splitLines, margin + 4, y + 12);

      y += boxH + 5;
    });
  }

  // SECTION 6: ADAPTIVE RECOMMENDATIONS
  if (y > pageHeight - 45) {
    doc.addPage();
    drawHeader();
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('4. Actionable Biofeedback Adaptation Protocols', margin, y);
  y += 5;

  const recs = data.comparisonResult.recommendations || [];
  recs.forEach((r, idx) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const splitRec = doc.splitTextToSize(r, contentWidth - 14);
    const boxH = Math.max(12, splitRec.length * 4.5 + 6);

    if (y + boxH > pageHeight - 20) {
      doc.addPage();
      drawHeader();
    }

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
    doc.setLineWidth(0.3);
    doc.roundedRect(margin, y, contentWidth, boxH, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.text(`${idx + 1}.`, margin + 3, y + 6);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
    doc.text(splitRec, margin + 8, y + 6);

    y += boxH + 4;
  });

  y += 4;

  // AUTOMATED REPORT VERIFICATION
  if (y > pageHeight - 25) {
    doc.addPage();
    drawHeader();
  }

  doc.setDrawColor(borderColor[0], borderColor[1], borderColor[2]);
  doc.setLineWidth(0.4);
  doc.line(margin, y, margin + contentWidth, y);
  y += 5;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text('Automated Report Verification:', margin, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.text('Analysis Engine: Mind Monitor Dual-Session Comparison Engine', margin, y + 5.5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text('Verification Status: Dual-Session Delta & Correlation Verified', pageWidth - margin, y + 5.5, { align: 'right' });

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(i, totalPages);
  }

  doc.save(`EEG_Comparative_Neuro_Report_${data.reportId}.pdf`);
};
